curl -b cookies.txt -c cookies.txt  https://www.space-track.org/ajaxauth/login 'identity=kalvis.salmins@lu.lv&password=Sentinel_2017.1884'

###

curl --cookie  cookies.txt https://www.space-track.org/basicspacedata/query/class/tip/NORAD_CAT_ID/60,38462,38351/format/html
